# Generated by Django 2.1.8 on 2020-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.CharField(default='', max_length=128),
        ),
    ]
