# Generated by Django 2.1.8 on 2020-06-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='interview',
        ),
        migrations.RemoveField(
            model_name='work',
            name='request',
        ),
        migrations.RemoveField(
            model_name='work',
            name='salaryhigh',
        ),
        migrations.RemoveField(
            model_name='work',
            name='salarylow',
        ),
        migrations.RemoveField(
            model_name='work',
            name='url',
        ),
        migrations.AddField(
            model_name='work',
            name='exp',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='work',
            name='salary',
            field=models.CharField(default='', max_length=128),
        ),
    ]
