# Generated by Django 2.1.8 on 2020-06-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20200626_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='timeend',
        ),
        migrations.RemoveField(
            model_name='order',
            name='timestart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='course_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
    ]
