# Generated by Django 2.1.8 on 2020-06-27 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20200627_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='course_id',
            field=models.IntegerField(),
        ),
    ]
