# Generated by Django 2.1.8 on 2020-06-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200627_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('teacher', models.CharField(default='', max_length=128)),
                ('time', models.CharField(default='', max_length=128)),
                ('originalprice', models.IntegerField()),
                ('currentprice', models.IntegerField()),
                ('info', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
