# Generated by Django 2.1.8 on 2020-06-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='teacher_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='currentprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='originalprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='course_id',
            field=models.IntegerField(default=0),
        ),
    ]
