# Generated by Django 2.1.8 on 2020-06-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20200627_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('info', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
